spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/USER_SERVICE
    username: user
    password: user123
    dbcp2:
      validation-query: SELECT 1
      
  jpa:    
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update  